import { CalibrationData, GameProfile, MonitorProfile } from '../types';

export type ConfigFormat = 
  | 'demulshooter'
  | 'mame_game_cfg'
  | 'mame_ctrlr_ini'
  | 'pcsx2'
  | 'model2'
  | 'teknoparrot'
  | 'retroarch_snes9x_opt'
  | 'retroarch_game_rmp'
  | 'retroarch_cfg_snippet'
  | 'vjoy';

export interface GeneratedConfigResult {
  fileName: string;
  fileFormat: string;
  content: string;
  description: string;
  installLocation: string;
}

/**
 * Calculates normalized coordinate ranges and calibration offsets for P1 & P2
 */
function getCalibBounds(calib?: CalibrationData) {
  if (!calib || !calib.isCalibrated) {
    return {
      minX: 850,
      maxX: 9150,
      minY: 850,
      maxY: 9150,
      spanX: 8300,
      spanY: 8300,
      centerX: 5000,
      centerY: 5000,
      matrixStr: '1.0,0,0,0,1.0,0,0,0,1.0',
    };
  }

  const minX = calib.optimalRanges?.minX ?? Math.min(calib.tl.x, calib.bl.x);
  const maxX = calib.optimalRanges?.maxX ?? Math.max(calib.tr.x, calib.br.x);
  const minY = calib.optimalRanges?.minY ?? Math.min(calib.tl.y, calib.tr.y);
  const maxY = calib.optimalRanges?.maxY ?? Math.max(calib.bl.y, calib.br.y);
  const spanX = Math.max(500, maxX - minX);
  const spanY = Math.max(500, maxY - minY);
  const centerX = Math.round((minX + maxX) / 2);
  const centerY = Math.round((minY + maxY) / 2);

  const matrixStr = calib.homographyMatrix 
    ? calib.homographyMatrix.map(v => v.toFixed(6)).join(',')
    : '1.0,0,0,0,1.0,0,0,0,1.0';

  return { minX, maxX, minY, maxY, spanX, spanY, centerX, centerY, matrixStr };
}

/**
 * Generates DemulShooter.ini with P1 & P2 calibration, VID/PID, and game target parameters
 */
export function generateDemulShooterIni(
  profile: GameProfile,
  calibP1: CalibrationData,
  calibP2: CalibrationData,
  monitor: MonitorProfile,
  deadzone = 8,
  sensitivity = 1.0
): GeneratedConfigResult {
  const p1 = getCalibBounds(calibP1);
  const p2 = getCalibBounds(calibP2);

  const content = `; ==============================================================================
; DemulShooter Configuration File
; Auto-generated by G'AIM'E PC Bridge
; Target Profile: ${profile.name} (${profile.system})
; Rom Target: ${profile.romName} | Launch Arg: ${profile.demulShooterTarget || `-target=generic -rom=${profile.romName}`}
; Display Resolution: ${monitor.width}x${monitor.height} (${monitor.name})
; ==============================================================================

[General]
VerbosityLevel = 1
DisableWindowPositionHook = 0
OffscreenReload = ${profile.offscreenReload ? '1' : '0'}
Deadzone = ${deadzone}
SensitivityMultiplier = ${sensitivity.toFixed(2)}

; --- PLAYER 1 (G'AIM'E v1 - VID_2E2C / PID_0631) ---
[Player1]
Device_VID = 0x2E2C
Device_PID = 0x0631
InputType = RawHID
DeviceID = 0
Calib_MinX = ${p1.minX}
Calib_MaxX = ${p1.maxX}
Calib_MinY = ${p1.minY}
Calib_MaxY = ${p1.maxY}
Calib_SpanX = ${p1.spanX}
Calib_SpanY = ${p1.spanY}
Calib_CenterX = ${p1.centerX}
Calib_CenterY = ${p1.centerY}
HomographyMatrix = ${p1.matrixStr}
TriggerButton = 1
ReloadButton = 2
ActionPedalButton = 3
OffscreenReloadOffset = 300

; --- PLAYER 2 (G'AIM'E v1 / vJoy Device 2) ---
[Player2]
Device_VID = 0x2E2C
Device_PID = 0x0631
InputType = RawHID
DeviceID = 1
Calib_MinX = ${p2.minX}
Calib_MaxX = ${p2.maxX}
Calib_MinY = ${p2.minY}
Calib_MaxY = ${p2.maxY}
Calib_SpanX = ${p2.spanX}
Calib_SpanY = ${p2.spanY}
Calib_CenterX = ${p2.centerX}
Calib_CenterY = ${p2.centerY}
HomographyMatrix = ${p2.matrixStr}
TriggerButton = 1
ReloadButton = 2
ActionPedalButton = 3

; --- ACTIVE GAME TARGET RULE ---
[${profile.romName.toUpperCase()}]
TargetSystem = ${profile.emulator}
GameName = ${profile.name}
PedalMode = ${profile.pedalAction}
CustomParameters = ${profile.demulShooterTarget || ''}
ScreenAspect = ${(monitor.width / monitor.height).toFixed(4)}
`;

  return {
    fileName: 'DemulShooter.ini',
    fileFormat: 'ini',
    content,
    description: 'Konfiguracja DemulShooter ze zmapowanymi zakresami matrycy RAW dla Gracza 1 i Gracza 2',
    installLocation: 'Folder główny DemulShooter (obok DemulShooter.exe / DemulShooter_GUI.exe)',
  };
}

/**
 * Generates MAME game-specific XML configuration (<rom>.cfg or default.cfg)
 */
export function generateMameGameCfg(
  profile: GameProfile,
  calibP1: CalibrationData,
  calibP2: CalibrationData,
  monitor: MonitorProfile
): GeneratedConfigResult {
  const p1 = getCalibBounds(calibP1);
  const p2 = getCalibBounds(calibP2);

  const content = `﻿<?xml version="1.0"?>
<!-- MAME Controller Configuration for ${profile.name} (${profile.romName}) -->
<!-- Generated by G'AIM'E PC Bridge with calibrated lightgun coordinates -->
<mameconfig version="10">
    <system name="${profile.romName}">
        <input>
            <!-- PLAYER 1 LIGHTGUN CALIBRATION & INPUTS -->
            <port tag=":P1_LIGHTGUN_X" type="P1_LIGHTGUN_X" mask="65535" defvalue="0">
                <newseq type="standard">
                    GUNCODE_1_X
                </newseq>
            </port>
            <port tag=":P1_LIGHTGUN_Y" type="P1_LIGHTGUN_Y" mask="65535" defvalue="0">
                <newseq type="standard">
                    GUNCODE_1_Y
                </newseq>
            </port>
            <port tag=":P1_BUTTON1" type="P1_BUTTON1" mask="1" defvalue="0">
                <newseq type="standard">
                    GUNCODE_1_BUTTON1 OR MOUSECODE_1_BUTTON1
                </newseq>
            </port>
            <port tag=":P1_BUTTON2" type="P1_BUTTON2" mask="2" defvalue="0">
                <newseq type="standard">
                    GUNCODE_1_BUTTON2 OR KEYCODE_SPACE <!-- Pedał krycia / przeładowania -->
                </newseq>
            </port>
            <port tag=":P1_START" type="START1" mask="1" defvalue="0">
                <newseq type="standard">
                    KEYCODE_1 OR GUNCODE_1_BUTTON3
                </newseq>
            </port>
            <port tag=":COIN1" type="COIN1" mask="1" defvalue="0">
                <newseq type="standard">
                    KEYCODE_5 OR GUNCODE_1_BUTTON4
                </newseq>
            </port>

            <!-- PLAYER 2 LIGHTGUN CALIBRATION & INPUTS -->
            <port tag=":P2_LIGHTGUN_X" type="P2_LIGHTGUN_X" mask="65535" defvalue="0">
                <newseq type="standard">
                    GUNCODE_2_X
                </newseq>
            </port>
            <port tag=":P2_LIGHTGUN_Y" type="P2_LIGHTGUN_Y" mask="65535" defvalue="0">
                <newseq type="standard">
                    GUNCODE_2_Y
                </newseq>
            </port>
            <port tag=":P2_BUTTON1" type="P2_BUTTON1" mask="1" defvalue="0">
                <newseq type="standard">
                    GUNCODE_2_BUTTON1 OR MOUSECODE_2_BUTTON1
                </newseq>
            </port>
            <port tag=":P2_BUTTON2" type="P2_BUTTON2" mask="2" defvalue="0">
                <newseq type="standard">
                    GUNCODE_2_BUTTON2 OR KEYCODE_LSHIFT
                </newseq>
            </port>
        </input>
        <!-- CALIBRATION METADATA REFERENCE -->
        <!-- P1 Bounds: X=[${p1.minX}..${p1.maxX}], Y=[${p1.minY}..${p1.maxY}], Screen: ${monitor.width}x${monitor.height} -->
        <!-- P2 Bounds: X=[${p2.minX}..${p2.maxX}], Y=[${p2.minY}..${p2.maxY}] -->
    </system>
</mameconfig>
`;

  return {
    fileName: `${profile.romName}.cfg`,
    fileFormat: 'xml/cfg',
    content,
    description: `Plik konfiguracyjny wejść MAME dedykowany dla gry ${profile.name}`,
    installLocation: `Folder MAME /cfg/${profile.romName}.cfg (lub /cfg/default.cfg)`,
  };
}

/**
 * Generates MAME controller ini file (mame.ini or ctrlr/gaime_lightgun.ini)
 */
export function generateMameCtrlrIni(
  profile: GameProfile,
  monitor: MonitorProfile,
  deadzone = 8
): GeneratedConfigResult {
  const content = `# ==============================================================================
# MAME Core Lightgun & Mouse Configuration (mame.ini / ctrlr profile)
# Generated by G'AIM'E PC Bridge
# ==============================================================================

# CORE INPUT OPTIONS
#
coin_lockout              1
ctrlr                     gaime_lightgun
mouse                     1
joystick                  1
lightgun                  1
multikeyboard             1
multimouse                1
steadykey                 0
ui_active                 0
offscreen_reload          ${profile.offscreenReload ? '1' : '0'}

# CORE INPUT AUTOMATIC ENABLE OPTIONS
#
paddle_device             mouse
adstick_device            lightgun
pedal_device              keyboard
dial_device               mouse
trackball_device          mouse
lightgun_device           lightgun
positional_device         lightgun
mouse_device              mouse

# LIGHTGUN ACCELERATION & SENSITIVITY
#
lightgun_reload_button    1
lightgun_deadzone         0.${deadzone.toString().padStart(2, '0')}
lightgun_analog_speed     1
lightgun_reverse_x        0
lightgun_reverse_y        0

# OSD VIDEO OPTIONS
#
resolution                ${monitor.width}x${monitor.height}
window                    0
maximize                  1
waitvsync                 1
syncrefresh               1
`;

  return {
    fileName: 'gaime_lightgun.ini',
    fileFormat: 'ini',
    content,
    description: 'Plik definicji kontrolera lightgun dla MAME (włączone multimouse i obsługa 2 pistoletów)',
    installLocation: 'Folder MAME /ctrlr/gaime_lightgun.ini (oraz dopisek ctrlr gaime_lightgun w mame.ini)',
  };
}

/**
 * Generates PCSX2 Controllers.ini with GunCon2 bindings for P1 & P2
 */
export function generatePcsx2Config(
  profile: GameProfile,
  calibP1: CalibrationData,
  calibP2: CalibrationData
): GeneratedConfigResult {
  const p1 = getCalibBounds(calibP1);
  const p2 = getCalibBounds(calibP2);

  const content = `; PCSX2 Controller & Lightgun Configuration
; Generated by G'AIM'E PC Bridge for ${profile.name}
; Auto-calibrated bounds: P1 X=[${p1.minX}..${p1.maxX}] Y=[${p1.minY}..${p1.maxY}]

[Pad1]
Type = GunCon2
GunCon2_Pointer = Mouse:AbsolutePointer
GunCon2_Trigger = Mouse:Left
GunCon2_A = Mouse:Middle
GunCon2_B = Mouse:Right
GunCon2_Start = Keyboard:Return
GunCon2_Select = Keyboard:Space
GunCon2_Pedal = Keyboard:Space # Pedał USB lub klawisz krycia
GunCon2_OffscreenReload = ${profile.offscreenReload ? '1' : '0'}
GunCon2_CalibMinX = ${p1.minX}
GunCon2_CalibMaxX = ${p1.maxX}
GunCon2_CalibMinY = ${p1.minY}
GunCon2_CalibMaxY = ${p1.maxY}

[Pad2]
Type = GunCon2
GunCon2_Pointer = SDL-1:Pointer # Drugi pistolet P2 przez vJoy/HID
GunCon2_Trigger = SDL-1:Button0
GunCon2_A = SDL-1:Button1
GunCon2_B = SDL-1:Button2
GunCon2_Pedal = Keyboard:LeftShift
GunCon2_CalibMinX = ${p2.minX}
GunCon2_CalibMaxX = ${p2.maxX}
GunCon2_CalibMinY = ${p2.minY}
GunCon2_CalibMaxY = ${p2.maxY}
`;

  return {
    fileName: 'Controllers.ini',
    fileFormat: 'ini',
    content,
    description: 'Plik konfiguracyjny GunCon 2 dla emulatora PCSX2 (PlayStation 2)',
    installLocation: 'Folder PCSX2 /inis/Controllers.ini',
  };
}

/**
 * Generates Sega Model 2 Emulator EMULATOR.INI
 */
export function generateModel2Config(
  profile: GameProfile,
  monitor: MonitorProfile
): GeneratedConfigResult {
  const content = `; Sega Model 2 Emulator Configuration
; Configured for G'AIM'E Lightgun Bridge
; Active Target: ${profile.name} (${profile.romName})

[Renderer]
FullMode = 4
ScreenWidth = ${monitor.width}
ScreenHeight = ${monitor.height}
AutoFull = 1
DrawCross = 0
ForceSync = 1

[Input]
RawInput = 1
CrossHair = 0
OffscreenReload = ${profile.offscreenReload ? '1' : '0'}

; Game Input Mapping:
; Virtua Cop 1 & 2 / The House of the Dead
P1_Gun_X = MOUSE1_X
P1_Gun_Y = MOUSE1_Y
P1_Trigger = MOUSE1_BUTTON1
P1_Reload = MOUSE1_BUTTON2
P1_Pedal = KEY_SPACE
P1_Start = KEY_1
P1_Coin = KEY_5

P2_Gun_X = MOUSE2_X
P2_Gun_Y = MOUSE2_Y
P2_Trigger = MOUSE2_BUTTON1
P2_Reload = MOUSE2_BUTTON2
P2_Start = KEY_2
P2_Coin = KEY_6
`;

  return {
    fileName: 'EMULATOR.INI',
    fileFormat: 'ini',
    content,
    description: 'Konfiguracja Sega Model 2 Emulator (Virtua Cop 1/2, The House of the Dead)',
    installLocation: 'Katalog emulatora Model 2 (obok emulator.exe)',
  };
}

/**
 * Generates TeknoParrot controller XML profile
 */
export function generateTeknoParrotConfig(
  profile: GameProfile,
  calibP1: CalibrationData,
  monitor: MonitorProfile
): GeneratedConfigResult {
  const p1 = getCalibBounds(calibP1);

  const content = `<?xml version="1.0" encoding="utf-8"?>
<!-- TeknoParrot Lightgun Profile for ${profile.name} (${profile.romName}) -->
<!-- Generated by G'AIM'E PC Bridge -->
<GameProfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <GameName>${profile.name}</GameName>
  <EmulationProfile>${profile.romName}</EmulationProfile>
  <InputApi>RawInput</InputApi>
  <GunCalibration>
    <MinX>${p1.minX}</MinX>
    <MaxX>${p1.maxX}</MaxX>
    <MinY>${p1.minY}</MinY>
    <MaxY>${p1.maxY}</MaxY>
    <ScreenWidth>${monitor.width}</ScreenWidth>
    <ScreenHeight>${monitor.height}</ScreenHeight>
  </GunCalibration>
  <ButtonBindings>
    <Trigger>RawMouseLeft</Trigger>
    <Reload>RawMouseRight</Reload>
    <ActionPedal>Space</ActionPedal>
    <Start>1</Start>
    <Coin>5</Coin>
  </ButtonBindings>
  <DemulShooterHook>${profile.demulShooterTarget || 'lindbergh'}</DemulShooterHook>
</GameProfile>
`;

  return {
    fileName: `${profile.romName}.xml`,
    fileFormat: 'xml',
    content,
    description: `Profil sterowania TeknoParrot dla gry ${profile.name}`,
    installLocation: `Folder TeknoParrot /UserProfiles/${profile.romName}.xml`,
  };
}

/**
 * Generates vJoy device mapping configuration
 */
export function generateVJoyConfig(
  calibP1: CalibrationData,
  calibP2: CalibrationData
): GeneratedConfigResult {
  const p1 = getCalibBounds(calibP1);
  const p2 = getCalibBounds(calibP2);

  const content = `; vJoy Virtual Lightgun Bridge Configuration
; Generated by G'AIM'E PC Bridge
; Maps G'AIM'E USB HID packets to virtual DirectInput/XInput axes (X, Y)

[Device1_P1]
TargetVJoyId = 1
AxisX = Axis_X
AxisY = Axis_Y
AxisX_Min = 0
AxisX_Max = 32767
AxisY_Min = 0
AxisY_Max = 32767
CalibRawMinX = ${p1.minX}
CalibRawMaxX = ${p1.maxX}
CalibRawMinY = ${p1.minY}
CalibRawMaxY = ${p1.maxY}
Button_Trigger = 1
Button_Reload = 2
Button_Pedal = 3

[Device2_P2]
TargetVJoyId = 2
AxisX = Axis_X
AxisY = Axis_Y
AxisX_Min = 0
AxisX_Max = 32767
AxisY_Min = 0
AxisY_Max = 32767
CalibRawMinX = ${p2.minX}
CalibRawMaxX = ${p2.maxX}
CalibRawMinY = ${p2.minY}
CalibRawMaxY = ${p2.maxY}
Button_Trigger = 1
Button_Reload = 2
Button_Pedal = 3
`;

  return {
    fileName: 'vJoy_Gaime.ini',
    fileFormat: 'ini',
    content,
    description: 'Mapowanie osi analogowych wirtualnego joysticka vJoy dla emulatorów bez natywnej myszy',
    installLocation: 'Katalog główny vJoy lub podfolder bridge',
  };
}

/**
 * Generates RetroArch core options file snes9x.opt for Snes9x 1.62.3
 */
export function generateRetroArchSnes9xOpt(
  profile: GameProfile,
  calibP1: CalibrationData,
  monitor: MonitorProfile
): GeneratedConfigResult {
  const isJustifier = profile.id === 'lethal_enforcers_snes';
  const p1 = getCalibBounds(calibP1);

  const content = `# ==============================================================================
# RetroArch Core Options: Snes9x 1.62.3 (snes9x.opt)
# Auto-generated by G'AIM'E PC Bridge for ${profile.name}
# Monitor: ${monitor.name} (${monitor.width}x${monitor.height})
# Target Core: Snes9x (Current / 1.62.3)
# ==============================================================================

# Lightgun & Crosshair Mode
snes9x_lightgun_mode = "Lightgun"
snes9x_superscope_crosshair = "${isJustifier ? '0' : '2'}"
snes9x_superscope_color = "0"
snes9x_justifier_crosshair = "${isJustifier ? '2' : '0'}"
snes9x_justifier1_color = "0"
snes9x_justifier2_color = "1"

# Crucial Video & Aspect Ratio Settings
# (Overscan MUST be disabled to preserve exact 256x224 1:1 hardware pixel ratio)
snes9x_overscan = "disabled"
snes9x_aspect_ratio = "4:3"
snes9x_hires_blend = "disabled"
snes9x_region = "auto"

# Rendering Layers (Ensure all sprite & gun layers are active)
snes9x_layer_1 = "enabled"
snes9x_layer_2 = "enabled"
snes9x_layer_3 = "enabled"
snes9x_layer_4 = "enabled"
snes9x_sprites = "enabled"
snes9x_sndchan_1 = "enabled"
snes9x_sndchan_2 = "enabled"
snes9x_sndchan_3 = "enabled"
snes9x_sndchan_4 = "enabled"
snes9x_sndchan_5 = "enabled"
snes9x_sndchan_6 = "enabled"
snes9x_sndchan_7 = "enabled"
snes9x_sndchan_8 = "enabled"

# G'AIM'E Calibration Reference Matrix:
# MinX: ${p1.minX} MaxX: ${p1.maxX} | MinY: ${p1.minY} MaxY: ${p1.maxY}
`;

  return {
    fileName: 'snes9x.opt',
    fileFormat: 'opt',
    content,
    description: "Opcje rdzenia Snes9x 1.62.3 w RetroArch (włączony tryb Lightgun, celownik i wyłączony overscan dla skali 1:1)",
    installLocation: 'retroarch/config/Snes9x/Snes9x.opt (lub snes9x.opt)',
  };
}

/**
 * Generates RetroArch Remap file (.rmp) for Snes9x Port 2 Super Scope / Justifier
 */
export function generateRetroArchRemap(
  profile: GameProfile
): GeneratedConfigResult {
  const isJustifier = profile.id === 'lethal_enforcers_snes';
  const deviceId = isJustifier ? '516' : '260'; // 260 = SuperScope, 516 = Justifier
  const deviceName = isJustifier ? 'Konami Justifier' : 'Nintendo Super Scope';

  const content = `# ==============================================================================
# RetroArch Input Remap: Snes9x 1.62.3
# Target: ${profile.name} (${deviceName})
# File: Snes9x.rmp
# ==============================================================================

# Port 1: Standard SNES Controller (D-Pad, Start, Select)
input_libretro_device_p1 = "1"

# Port 2: ${deviceName} (Device ID: ${deviceId})
# In SNES hardware, Super Scope and Justifier ALWAYS connect to Controller Port 2
input_libretro_device_p2 = "${deviceId}"

# G'AIM'E Absolute Lightgun / Raw Mouse Mappings for Player 2
input_player2_mouse_index = "0"
input_player2_gun_trigger = "mouse:1"
input_player2_gun_offscreen_shot = "mouse:2"
input_player2_gun_aux_a = "mouse:3"
input_player2_gun_aux_b = "space"
input_player2_gun_start = "enter"
input_player2_gun_select = "escape"

# Remap version signature
input_remap_port_p1 = "0"
input_remap_port_p2 = "1"
`;

  return {
    fileName: 'Snes9x.rmp',
    fileFormat: 'rmp',
    content,
    description: `Plik remapowania wejść RetroArch dla Snes9x (Port 2 jako ${deviceName} - ID ${deviceId})`,
    installLocation: 'retroarch/config/remaps/Snes9x/Snes9x.rmp',
  };
}

/**
 * Generates retroarch.cfg lightgun raw input snippet
 */
export function generateRetroArchCfgSnippet(
  calibP1: CalibrationData,
  monitor: MonitorProfile,
  deadzone = 4,
  sensitivity = 1.0
): GeneratedConfigResult {
  const p1 = getCalibBounds(calibP1);

  const content = `# ==============================================================================
# RetroArch Main Configuration (retroarch.cfg) - Lightgun & Mouse Setup
# Compatible with G'AIM'E v1 Lightgun & Snes9x 1.62.3
# Monitor Resolution: ${monitor.width}x${monitor.height}
# ==============================================================================

# Input Driver: Raw Input provides absolute coordinates without OS cursor scaling
input_driver = "raw"

# Mouse & Lightgun Driver Configuration
input_mouse_index = "0"
input_player1_mouse_index = "0"
input_player2_mouse_index = "0"
input_auto_mouse_grab = "true"

# Lightgun Button Mapping (P2 Super Scope / Justifier)
input_player2_gun_trigger_mbtn = "1"
input_player2_gun_offscreen_shot_mbtn = "2"
input_player2_gun_aux_a_mbtn = "3"
input_player2_gun_start_btn = "nul"

# Video & Fullscreen (prevents cursor displacement)
video_fullscreen = "true"
video_windowed_fullscreen = "true"
video_scale_integer = "false"
video_aspect_ratio_auto = "false"

# G'AIM'E Tuned Parameters:
# Calibrated Bounds: X[${p1.minX} - ${p1.maxX}], Y[${p1.minY} - ${p1.maxY}]
# Deadzone: ${deadzone}px | Sensitivity: ${sensitivity.toFixed(2)}x
`;

  return {
    fileName: 'retroarch_lightgun_snippet.cfg',
    fileFormat: 'cfg',
    content,
    description: "Fragment konfiguracji retroarch.cfg z obsługą RawInput dla pistoletów G'AIM'E",
    installLocation: 'retroarch/retroarch.cfg (wklej do głównego pliku konfiguracyjnego)',
  };
}

/**
 * Master generator dispatcher
 */
export function generateConfigForFormat(
  format: ConfigFormat,
  profile: GameProfile,
  calibP1: CalibrationData,
  calibP2: CalibrationData,
  monitor: MonitorProfile,
  deadzone = 8,
  sensitivity = 1.0
): GeneratedConfigResult {
  switch (format) {
    case 'demulshooter':
      return generateDemulShooterIni(profile, calibP1, calibP2, monitor, deadzone, sensitivity);
    case 'mame_game_cfg':
      return generateMameGameCfg(profile, calibP1, calibP2, monitor);
    case 'mame_ctrlr_ini':
      return generateMameCtrlrIni(profile, monitor, deadzone);
    case 'pcsx2':
      return generatePcsx2Config(profile, calibP1, calibP2);
    case 'model2':
      return generateModel2Config(profile, monitor);
    case 'teknoparrot':
      return generateTeknoParrotConfig(profile, calibP1, monitor);
    case 'retroarch_snes9x_opt':
      return generateRetroArchSnes9xOpt(profile, calibP1, monitor);
    case 'retroarch_game_rmp':
      return generateRetroArchRemap(profile);
    case 'retroarch_cfg_snippet':
      return generateRetroArchCfgSnippet(calibP1, monitor, deadzone, sensitivity);
    case 'vjoy':
      return generateVJoyConfig(calibP1, calibP2);
    default:
      return generateDemulShooterIni(profile, calibP1, calibP2, monitor, deadzone, sensitivity);
  }
}

/**
 * Helper to download any generated config directly from the browser
 */
export function downloadConfigFile(fileName: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
